<?php
return array(
    'AU' => 'en' ,
    'AT' => 'de' ,
    'BE' => 'fr' ,
    'BR' => 'pt' ,
    'CA' => 'en' ,
    'CN' => 'zh' ,
    'CZ' => 'cs' ,
    'DK' => 'da' ,
    'FR' => 'fr' ,
    'DE' => 'de' ,
    'IN' => 'hi' ,
    'IT' => 'it' ,
    'JP' => 'ja' ,
    'MX' => 'es' ,
    'NL' => 'nl' ,
    'NO' => 'nb' ,
    'PL' => 'pl' ,
    'RU' => 'ru' ,
    'ES' => 'ca' ,
    'SE' => 'sv' ,
    'CH' => 'fr' ,
    'TR' => 'tr' ,
    'GB' => 'cy' ,
    'US' => 'en' ,
);