<?php
return array(
    'AU' => 'AUD' ,
    'AT' => 'EUR' ,
    'BE' => 'EUR' ,
    'BR' => 'BRL' ,
    'CA' => 'CAD' ,
    'CN' => 'CNY' ,
    'CZ' => 'CZK' ,
    'DK' => 'DKK' ,
    'FR' => 'EUR' ,
    'DE' => 'EUR' ,
    'IN' => 'INR' ,
    'IT' => 'EUR' ,
    'JP' => 'JPY' ,
    'MX' => 'MXN' ,
    'NL' => 'EUR' ,
    'NO' => 'NOK' ,
    'PL' => 'PLN' ,
    'RU' => 'RUB' ,
    'ES' => 'EUR' ,
    'SE' => 'SEK' ,
    'CH' => 'CHF' ,
    'TR' => 'TRY' ,
    'GB' => 'GBP' ,
    'US' => 'USD' ,
);